### PR TITLE
adding support for Gigabyte M28U with MBP 16 2019

### PR DESCRIPTION
**Pull request by jacobhmurphy**

### CODE REVIEW

**Comment by jakebellacera** [comment]
@jacobhmurphy just curious, how are you connected to the monitor? I see `Thunderbolt/DisplayPort` but it's not clear to me if that is a Thunderbolt USB-C cable or a Thunderbolt to DisplayPort cable. If you could let me know exactly which cable you have connected as well that would be helpful. I just picked up my M28U and appear to have ran into snags with my 2019 16" MacBook Pro which has a 5300M (basically the step down from your model). Thanks!

**Comment by jacobhmurphy** [comment]
> @jacobhmurphy just curious, how are you connected to the monitor? I see `Thunderbolt/DisplayPort` but it's not clear to me if you're connected via USB-C or DisplayPort. If you could let me know exactly which cable you have connected as well that would be helpful. I just picked up my M28U and appear to have ran into snags with my 2019 16" MacBook Pro which has a 5300M (basically the step down from your model). Thanks!

I'm using this [Cable Matters USB-C to DisplayPort cable](https://www.amazon.com/gp/product/B01J6DT070/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1). It's currently connected via a CalDigit TS3 Plus dock through the Thunderbolt port on the dock. Perhaps Monterey may show the 120 Hz mode through the Displays preference pane since it supports variable-refresh rate, but if you're on Big Sur it might be helpful to install SwitchResX as Big Sur might not offer 120 Hz HiDPI via the Displays preference pane.

**Comment by AgapovOne** [comment]
@tonsky I think it would be great to add which cable also provided support for any resolution. Like 5K@120hz only with Thunderbolt-DisplayPort, not any HDMI setup. It would help to choose proper expensive cable that I should buy with a monitor.

**Comment by tonsky** [comment]
I am pretty sure it was [in the article](https://tonsky.me/blog/monitors/): 4k@120Hz+ only works via DisplayPort. The particular cable doesn’t matter

**Comment by MainasuK** [comment]
I use the similar setup:
MacBook Pro 14 inch --(thunderbolt)--> CalDigit TS3
CalDigit TS3 thunderbolt port --(Type-C-to-DisplayProt 1.4)--> LG 27GP950-B (4K 120Hz without DSC or 4K 95Hz with DSC)
CalDigit TS3 DisplayPort (1.2) --(DisplayPort 1.4)--> LG 27UL650-W (4K 60Hz)

I think the dock bandwidth is almost drain out because the dock cannot output 144Hz but 95Hz via DP 1.4 with DSC. Only the directly connect make 4K 144Hz works.

**Pull request merged**
