### PR TITLE
Dell G3223Q works with Macbook Air M1

### PR DESCRIPTION
**Pull request by faaarmer**
CleanShot 2022-04-19 at 10 05 51@2x
CleanShot 2022-04-19 at 10 06 01@2x

Using the same USB-C to DisplayPort cable as https://github.com/tonsky/tonsky.github.io/pull/68

### CODE REVIEW

**Comment by tonsky** [comment]
Thanks!

**Comment by mseflek** [comment]
@faaarmer which cable did you use?

**Comment by faaarmer** [comment]
> @faaarmer which cable did you use?

I said what cable I used in the PR. 

I tried a USB-C to DP cable and multiple USB-C hubs with HDMI ports. All of the cables/hubs that I tried gave me 4K 144hz with my M1 MacBook Air.

**Comment by mseflek** [comment]
@faaarmer sorry, I meant what brand/model of cable specifically. I might be starting to lose my vision but you only mentioned that you used a usb-c to DP cable in both PRs, not which brand/model.

**Comment by faaarmer** [comment]
> @faaarmer sorry, I meant what brand/model of cable specifically. I might be starting to lose my vision but you only mentioned that you used a usb-c to DP cable in both PRs, not which brand/model.

Ahh ok. I can't find it on Amazon anymore but it was a "CHOETECH" branded cable.

**Pull request merged**
